stages:
  - lint
  - test

swiftlint:
  stage: lint
  tags: [ios]
  script:
    - brew install swiftlint || true
    - swiftlint lint --strict || true

unit_tests_simulator:
  stage: test
  tags: [ios]
  variables:
    LC_ALL: "en_US.UTF-8"
    LANG: "en_US.UTF-8"
    PROJECT: DigitalBank.xcodeproj
    SCHEME: DigitalBank
    DEST_SIM: platform=iOS Simulator,name=iPhone 16 Pro,OS=latest
  script:
    - which xcpretty || sudo gem install xcpretty --no-document
    - mkdir -p build
    - |
      xcodebuild \
        -project "$PROJECT" \
        -scheme "$SCHEME" \
        -destination "$DEST_SIM" \
        -enableCodeCoverage YES \
        test | xcpretty -c
