unit_tests_simulator:
  stage: test
  tags: [ios]
  variables:
    PROJECT: DigitalBank.xcodeproj
    SCHEME: DigitalBank
    DEST_SIM: platform=iOS Simulator,name=iPhone 16 Pro,OS=latest
  script:
    - brew install swiftlint || true
    - swiftlint
    - which xcpretty || sudo gem install xcpretty --no-document
    - mkdir -p build
    - |
      xcodebuild \
        -project "$PROJECT" \
        -scheme "$SCHEME" \
        -destination "$DEST_SIM" \
        -enableCodeCoverage YES \
        test | xcpretty -c
