unit_tests_simulator:
  stage: test
  tags: [ios]
  script:
    - which xcpretty || sudo gem install xcpretty --no-document
    - mkdir -p build
    - |
      xcodebuild \
        -project "$PROJECT" \
        -scheme "$SCHEME" \
        -destination "$DEST_SIM" \
        -enableCodeCoverage YES \
        -resultBundlePath build/TestResults.xcresult \
        test | xcpretty -c
  artifacts:
    when: always
    paths:
      - build/
