stages:
  - test

variables:
  PROJECT: DigitalBank.xcodeproj
  SCHEME: DigitalBank
  DEST_SIM: "platform=iOS Simulator,name=iPhone 16 Pro,OS=latest"

unit_tests_simulator:
  stage: test
  tags:
    - ios
  script:
    - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DEST_SIM" -enableCodeCoverage YES test -resultBundlePath build/ResultBundle.xcresult
  artifacts:
    when: always
    paths:
      - build/
    expire_in: 1 week
